spring.application.name: cloudflare-ddns

logging:
  file.name: /var/log/cloudflare-ddns/cloudflare-ddns.log
  logback.rollingpolicy:
    max-file-size: 100MB
    max-history: 10

spring.cloud.openfeign.okhttp.enabled: true

cloudflare:
  dns_trace:
    url: https://1.1.1.1/cdn-cgi/trace
    backup_url: https://1.0.0.1/cdn-cgi/trace
  api:
    root_url: https://api.cloudflare.com/client/v4/
    get_dns_records_path: /zones/{zone_id}/dns_records
    patch_record_path: /zones/{zone_id}/dns_records/{dns_record_id}
    token: api_token
    per_page: 100
  zones:
    - id: zone_id
      token: api_token
      domains:
        - yourdomain.com
        - api.yourdomain.com
