name: Release version
on:
  workflow_dispatch: # manual

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: maven

      - name: Build and test
        run: mvn clean verify

      - name: Release current version
        run: |
          git config user.email "cicd@github.com"
          git config user.name "CI/CD"
          echo VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')" >> $GITHUB_ENV
          mvn --batch-mode release:prepare

      - name: Push jar
        run: |
          mvn --batch-mode release:perform

      - name: Checkout tag
        run: git checkout cloudflare-ddns-${{ env.VERSION }}

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build native image arm64
        run: |
          docker run --rm --platform linux/arm64 \
            -v "$PWD:/app" -w /app \
            vegardit/graalvm-maven:latest-java21 \
            mvn -Pnative clean package native:compile-no-fork
          mv ./target/cloudflare-ddns ./target/cloudflare-ddns-arm64

      - name: Build native image amd64
        run: |
          docker run --rm --platform linux/amd64 \
            -v "$PWD:/app" -w /app \
            vegardit/graalvm-maven:latest-java21 \
            mvn -Pnative clean package native:compile-no-fork
          mv ./target/cloudflare-ddns ./target/cloudflare-ddns-amd64

      - name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: alexmihai1984/cloudflare-ddns:latest,alexmihai1984/cloudflare-ddns:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
