name: Release version
on:
  workflow_dispatch: # manual

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: maven

      - name: Build and test
        run: mvn clean verify

      - name: Release current version
        run: |
          git config user.email "cicd@github.com"
          git config user.name "CI/CD"
          mvn --batch-mode release:prepare
          export VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')"
          echo "Version: $VERSION ${VERSION}"

#      - name: Push package
#        run: |
#          mvn --batch-mode release:perform

      - name: Build native image
        run: |
          git checkout "cloudflare-ddns-{$VERSION}"
          mvn -Pnative clean package native:compile-no-fork

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: alexmihai1984/cloudflare-ddns:latest,alexmihai1984/cloudflare-ddns:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
