name: Release version
on:
  workflow_dispatch: # manual

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: maven

      - name: Build and Test
        run: mvn clean verify

      - name: Release current version
        run: |
          mvn release:prepare
          export VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          mvn -Pnative clean native:build
          mvn -Pnative deploy

      - name: Prepare next development version
        run: |
          mvn release:perform

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: alexmihai1984/cloudflare-ddns:latest,alexmihai1984/cloudflare-ddns:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
